---
# file: molecule/default/prepare.yml

- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update host apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install python3-minimal for ansible
      ansible.builtin.shell: "test -e /usr/bin/python3 || (apt update -y && apt install python3-minimal --no-install-recommends)"
      changed_when: false
      when: (ansible_facts['os_family'] == "Debian") or
            (ansible_facts['os_family'] == "Ubuntu")
